Micronaut with Reactive Mongodb and Ktor routing
this does not compile. yes, i'm sure there are conflicting implementations in the build.gradle file. But here's what it looks like. This project will be coming down soon
AppTest > initializationError FAILED
    io.micronaut.context.exceptions.BeanInstantiationException at DefaultBeanContext.java:2342
        Caused by: java.lang.NoSuchMethodError at Events.kt:24